[build]
  publish = "."

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
